theme: jekyll-theme-minimal
title: Open data in education
defaults:
    -
     scope:
         path: ""
     values:
         lang: en
         base-url: "/"
    -
     scope:
         path: fi
     values:
         layout: default_fi
         lang: fi
         base-url: "/fi/"
