title: Avoin data opetuskäyttöön - näillä ohjeilla alkuun!
url: "https://avoin-data-opas.github.io"
defaults:
    -
     scope:
         path: "fi"
     values:
         layout: default
         lang: fi
         base-url: "fi/"
    -
     scope:
         path: "se"
     values:
         lang: se
         base-url: "se/"
    -
     scope:
         path: "en"
     values:
         lang: en
         base-url: "en/"
         
plugins:
  - jekyll-redirect-from